# -*- coding: utf-8 -*-
"""Yoga-Pose-Classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fj9qWyfANm686uvfK-TNN24yngWxTgWH

# dataset: https://universe.roboflow.com/new-workspace-mujgg/yoga-pose
"""

# !pip install mediapipe

import os
import shutil

# !mkdir -p /content/dataset/train
# !mkdir -p /content/dataset/test
# !mkdir -p /content/dataset/valid

# !unzip -q /content/train.zip -d /content/dataset/train
# !unzip -q /content/test.zip -d /content/dataset/test
# !unzip -q /content/valid.zip -d /content/dataset/valid

# !find /content/dataset -type d -name "__MACOSX" -exec rm -rf {} +

# def auto_flatten(folder):
#     items = os.listdir(folder)
#     if len(items) == 1:
#         inner = os.path.join(folder, items[0])
#         if os.path.isdir(inner):
#             for cls in os.listdir(inner):
#                 shutil.move(os.path.join(inner, cls), folder)
#             shutil.rmtree(inner)

# auto_flatten("/content/dataset/train")
# auto_flatten("/content/dataset/test")
# auto_flatten("/content/dataset/valid")

# print(os.listdir("/content/dataset/train"))
# print(os.listdir("/content/dataset/test"))
# print(os.listdir("/content/dataset/valid"))

import os
import cv2
import matplotlib.pyplot as plt

# train_dir = "/content/dataset/train"
# classes = sorted(os.listdir(train_dir))

# classes = [c for c in classes if os.path.isdir(os.path.join(train_dir, c))]

# n = len(classes)
# cols = 5
# rows = (n // cols) + 1

# plt.figure(figsize=(20, 12))

# for i, cls in enumerate(classes):
#     class_path = os.path.join(train_dir, cls)
#     imgs = [f for f in os.listdir(class_path) if f.lower().endswith(('.jpg','.jpeg','.png'))]

#     if len(imgs) == 0:
#         continue

#     img_name = imgs[0]
#     img_path = os.path.join(class_path, img_name)

#     img = cv2.imread(img_path)
#     img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

#     plt.subplot(rows, cols, i + 1)
#     plt.imshow(img)
#     plt.title(f"{cls}\n{img_name}", fontsize=9)
#     plt.axis("off")

# plt.tight_layout()
# plt.show()

import cv2
import numpy as np
import mediapipe as mp
import pickle
import os
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score
import pandas as pd
# from google.colab import files
import matplotlib.pyplot as plt

mp_pose = mp.solutions.pose
mp_drawing = mp.solutions.drawing_utils

pose = mp_pose.Pose(
    static_image_mode=True,
    model_complexity=2,
    enable_segmentation=False,
    min_detection_confidence=0.5
)

def calculate_angle(p1, p2, p3):
    """
    Calculate angle between three points (p1-p2-p3)
    p2 is the vertex (middle point)

    Args:
        p1, p2, p3: landmarks with .x, .y attributes

    Returns:
        angle in degrees
    """
    # Convert to numpy arrays
    a = np.array([p1.x, p1.y])
    b = np.array([p2.x, p2.y])
    c = np.array([p3.x, p3.y])

    # Calculate vectors
    ba = a - b
    bc = c - b

    # Calculate angle using dot product
    cosine_angle = np.dot(ba, bc) / (np.linalg.norm(ba) * np.linalg.norm(bc) + 1e-6)
    angle = np.arccos(np.clip(cosine_angle, -1.0, 1.0))

    return np.degrees(angle)

def calculate_distance(p1, p2):
    """Calculate Euclidean distance between two points"""
    return np.sqrt((p1.x - p2.x)**2 + (p1.y - p2.y)**2)

def extract_pose_features(landmarks):
    """
    Extract comprehensive features from pose landmarks

    Returns:
        numpy array of ~50 features
    """
    features = []

    # Get landmark shortcuts
    lm = landmarks.landmark

    # ==================== ANGLE FEATURES ====================

    # Left arm angles
    left_shoulder_angle = calculate_angle(
        lm[mp_pose.PoseLandmark.LEFT_ELBOW],
        lm[mp_pose.PoseLandmark.LEFT_SHOULDER],
        lm[mp_pose.PoseLandmark.LEFT_HIP]
    )
    features.append(left_shoulder_angle)

    left_elbow_angle = calculate_angle(
        lm[mp_pose.PoseLandmark.LEFT_SHOULDER],
        lm[mp_pose.PoseLandmark.LEFT_ELBOW],
        lm[mp_pose.PoseLandmark.LEFT_WRIST]
    )
    features.append(left_elbow_angle)

    # Right arm angles
    right_shoulder_angle = calculate_angle(
        lm[mp_pose.PoseLandmark.RIGHT_ELBOW],
        lm[mp_pose.PoseLandmark.RIGHT_SHOULDER],
        lm[mp_pose.PoseLandmark.RIGHT_HIP]
    )
    features.append(right_shoulder_angle)

    right_elbow_angle = calculate_angle(
        lm[mp_pose.PoseLandmark.RIGHT_SHOULDER],
        lm[mp_pose.PoseLandmark.RIGHT_ELBOW],
        lm[mp_pose.PoseLandmark.RIGHT_WRIST]
    )
    features.append(right_elbow_angle)

    # Left leg angles
    left_hip_angle = calculate_angle(
        lm[mp_pose.PoseLandmark.LEFT_SHOULDER],
        lm[mp_pose.PoseLandmark.LEFT_HIP],
        lm[mp_pose.PoseLandmark.LEFT_KNEE]
    )
    features.append(left_hip_angle)

    left_knee_angle = calculate_angle(
        lm[mp_pose.PoseLandmark.LEFT_HIP],
        lm[mp_pose.PoseLandmark.LEFT_KNEE],
        lm[mp_pose.PoseLandmark.LEFT_ANKLE]
    )
    features.append(left_knee_angle)

    # Right leg angles
    right_hip_angle = calculate_angle(
        lm[mp_pose.PoseLandmark.RIGHT_SHOULDER],
        lm[mp_pose.PoseLandmark.RIGHT_HIP],
        lm[mp_pose.PoseLandmark.RIGHT_KNEE]
    )
    features.append(right_hip_angle)

    right_knee_angle = calculate_angle(
        lm[mp_pose.PoseLandmark.RIGHT_HIP],
        lm[mp_pose.PoseLandmark.RIGHT_KNEE],
        lm[mp_pose.PoseLandmark.RIGHT_ANKLE]
    )
    features.append(right_knee_angle)

    # Spine/torso angles
    spine_angle = calculate_angle(
        lm[mp_pose.PoseLandmark.LEFT_SHOULDER],
        lm[mp_pose.PoseLandmark.LEFT_HIP],
        lm[mp_pose.PoseLandmark.LEFT_KNEE]
    )
    features.append(spine_angle)

    # Neck angle
    neck_angle = calculate_angle(
        lm[mp_pose.PoseLandmark.LEFT_SHOULDER],
        lm[mp_pose.PoseLandmark.NOSE],
        lm[mp_pose.PoseLandmark.LEFT_EAR]
    )
    features.append(neck_angle)

    # ==================== DISTANCE FEATURES ====================

    # Hand distance (for poses with hands together)
    hand_distance = calculate_distance(
        lm[mp_pose.PoseLandmark.LEFT_WRIST],
        lm[mp_pose.PoseLandmark.RIGHT_WRIST]
    )
    features.append(hand_distance)

    # Foot distance (for poses with wide stance)
    foot_distance = calculate_distance(
        lm[mp_pose.PoseLandmark.LEFT_ANKLE],
        lm[mp_pose.PoseLandmark.RIGHT_ANKLE]
    )
    features.append(foot_distance)

    # ==================== RATIO FEATURES (body size normalized) ====================

    # Calculate body height (shoulder to ankle)
    body_height = calculate_distance(
        lm[mp_pose.PoseLandmark.LEFT_SHOULDER],
        lm[mp_pose.PoseLandmark.LEFT_ANKLE]
    )

    # Arm length ratios
    left_arm_length = calculate_distance(
        lm[mp_pose.PoseLandmark.LEFT_SHOULDER],
        lm[mp_pose.PoseLandmark.LEFT_WRIST]
    )
    features.append(left_arm_length / (body_height + 1e-6))

    right_arm_length = calculate_distance(
        lm[mp_pose.PoseLandmark.RIGHT_SHOULDER],
        lm[mp_pose.PoseLandmark.RIGHT_WRIST]
    )
    features.append(right_arm_length / (body_height + 1e-6))

    # ==================== POSITION FEATURES ====================

    # Y-coordinates (height) of key points (normalized)
    features.append(lm[mp_pose.PoseLandmark.LEFT_WRIST].y)
    features.append(lm[mp_pose.PoseLandmark.RIGHT_WRIST].y)
    features.append(lm[mp_pose.PoseLandmark.LEFT_ANKLE].y)
    features.append(lm[mp_pose.PoseLandmark.RIGHT_ANKLE].y)
    features.append(lm[mp_pose.PoseLandmark.NOSE].y)

    # X-coordinates (width) - for left/right alignment
    features.append(lm[mp_pose.PoseLandmark.LEFT_SHOULDER].x)
    features.append(lm[mp_pose.PoseLandmark.RIGHT_SHOULDER].x)

    # ==================== SYMMETRY FEATURES ====================

    # Arm symmetry (difference between left and right)
    arm_symmetry = abs(left_elbow_angle - right_elbow_angle)
    features.append(arm_symmetry)

    # Leg symmetry
    leg_symmetry = abs(left_knee_angle - right_knee_angle)
    features.append(leg_symmetry)

    # Shoulder level difference
    shoulder_level = abs(lm[mp_pose.PoseLandmark.LEFT_SHOULDER].y -
                         lm[mp_pose.PoseLandmark.RIGHT_SHOULDER].y)
    features.append(shoulder_level)

    # Hip level difference
    hip_level = abs(lm[mp_pose.PoseLandmark.LEFT_HIP].y -
                    lm[mp_pose.PoseLandmark.RIGHT_HIP].y)
    features.append(hip_level)

    return np.array(features)

def process_image(image_path):
    """
    Process a single image and extract pose features.
    Returns:
        features (numpy array) or None if pose not detected
    """
    image = cv2.imread(image_path)
    if image is None:
        return None

    img_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    # Run MediaPipe
    results = pose.process(img_rgb)

    # If no pose → skip image
    if not results.pose_landmarks:
        return None

    # Extract features from landmarks
    features = extract_pose_features(results.pose_landmarks)

    return features

def load_dataset(dataset_path):
    X = []
    y = []
    pose_names = []

    # Get all pose folders
    pose_folders = sorted([f for f in os.listdir(dataset_path)
                          if os.path.isdir(os.path.join(dataset_path, f))])

    print(f"\nFound {len(pose_folders)} pose classes:")
    for i, pose in enumerate(pose_folders):
        print(f"   {i}: {pose}")

    # Process each pose class
    for pose_idx, pose_name in enumerate(pose_folders):
        pose_path = os.path.join(dataset_path, pose_name)
        image_files = [f for f in os.listdir(pose_path)
                      if f.lower().endswith(('.jpg', '.jpeg', '.png'))]

        print(f"\nProcessing {pose_name}: {len(image_files)} images...")

        success_count = 0
        for img_file in image_files:
            img_path = os.path.join(pose_path, img_file)
            features = process_image(img_path)

            if features is not None:
                X.append(features)
                y.append(pose_idx)
                success_count += 1

        print(f"Successfully processed: {success_count}/{len(image_files)} images")
        pose_names.append(pose_name)

    X = np.array(X)
    y = np.array(y)

    print(f"\nDataset loaded: {X.shape[0]} samples, {X.shape[1]} features")

    return X, y, pose_names

import cv2
import matplotlib.pyplot as plt

def draw_landmarks_with_names(image_rgb, results):
    """Draw skeleton + keypoint labels on the image."""
    if not results.pose_landmarks:
        return image_rgb

    lm = results.pose_landmarks.landmark

    # Draw skeleton
    mp_drawing.draw_landmarks(
        image_rgb,
        results.pose_landmarks,
        mp_pose.POSE_CONNECTIONS
    )

    # Draw keypoint names
    h, w = image_rgb.shape[:2]
    for i, landmark in enumerate(lm):
        cx, cy = int(landmark.x * w), int(landmark.y * h)
        name = mp_pose.PoseLandmark(i).name
        cv2.putText(image_rgb, name, (cx+5, cy-5),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.35, (255,0,0), 1)
    return image_rgb

# test_images = [
#     "/content/dataset/train/adho mukha svanasana/1-1_png.rf.233030faa909816ea1588799cb60ab9d.jpg",
#     "/content/dataset/train/anjaneyasana/0-0_png.rf.513af8b6ad9c4e3d353c1d4748eb0250.jpg",
#     "/content/dataset/train/bhujangasana/0-0_png.rf.1004ad1308e3cfa2ffe2f98cb86f634d.jpg",

#     "/content/dataset/train/dhanurasana/1-0_png.rf.0bf92888e0901a8fe1ca500dde1413e0.jpg",
#     "/content/dataset/train/natarajasana/1-0_png.rf.1edbadcb8b06c14d51a2c8b88ebfece4.jpg",
#     "/content/dataset/train/padmasana/16-australia-yoga-life_png.rf.9d9ced9ff4eb3edfb9a0a80a04fb458a.jpg",

#     "/content/dataset/train/paschimottanasana/102-0_png.rf.0a27323b8cd858d60971a1484824a7fb.jpg",
#     "/content/dataset/train/phalakasana/16-0_png.rf.e5c9b3a69e08b0b3119a0c6caa47f52d.jpg",
#     "/content/dataset/train/salamba sarvangasana/0-0_png.rf.4ce33bd5cc1ab319d0213ff437e4bcbc.jpg",

#     "/content/dataset/train/setu bandha sarvangasana/1-0_png.rf.22b904115a1a259e1142527433932054.jpg",
#     "/content/dataset/train/tadasana/1-mountain-pose-567x567_png.rf.06ee81f52e8f5eefe08ee613441e553d.jpg",
#     "/content/dataset/train/uttanasana/1-2_png.rf.1c64ff268d67445bd09c8da1ea877c63.jpg",

#     "/content/dataset/train/utthita trikonasana/0-0_png.rf.0d5dfbe03dcb501490e996d5198d8bd9.jpg",
#     "/content/dataset/train/virabhadrasana ii/0-0_png.rf.106780cfe53ac54517a582df6b34adca.jpg",
#     "/content/dataset/train/vriksasana/0-1_png.rf.7319b564599ccc5d6304d2ed668a9fbd.jpg",

# ]


# plt.figure(figsize=(15, 20))
# cols = 3
# rows = 5

# for idx, img_path in enumerate(test_images[:15]):
#     image = cv2.imread(img_path)
#     if image is None:
#         print("Cannot read:", img_path)
#         continue

#     img_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

#     results = pose.process(img_rgb)
#     img_rgb = draw_landmarks_with_names(img_rgb, results)

#     plt.subplot(rows, cols, idx + 1)
#     plt.imshow(img_rgb)
#     plt.title(os.path.basename(img_path))
#     plt.axis("off")

# plt.tight_layout()
# plt.show()

import cv2
import os

def print_keypoints(img_path):
    image = cv2.imread(img_path)
    img_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    results = pose.process(img_rgb)

    if not results.pose_landmarks:
        print(f"\n{os.path.basename(img_path)} → NO POSE DETECTED")
        return

    lm = results.pose_landmarks.landmark

    print(f"\n============================")
    print(f"KEYPOINTS FOR: {os.path.basename(img_path)}")
    print(f"============================")

    for i, landmark in enumerate(lm):
        name = mp_pose.PoseLandmark(i).name
        print(f"{name}: x={landmark.x:.4f}, y={landmark.y:.4f}, "
              f"z={landmark.z:.4f}, vis={landmark.visibility:.4f}")

# # ---- RUN FOR 15 IMAGES ----
# for path in test_images:
#     print_keypoints(path)

# import os

# train_dir = "/content/dataset/train"

# classes = sorted([
#     c for c in os.listdir(train_dir)
#     if os.path.isdir(os.path.join(train_dir, c))
# ])

# print("📦 Dataset Summary:\n")

# total_images = 0

# for cls in classes:
#     cls_path = os.path.join(train_dir, cls)
#     imgs = [
#         f for f in os.listdir(cls_path)
#         if f.lower().endswith(('.jpg','.jpeg','.png'))
#     ]

#     count = len(imgs)
#     total_images += count

#     print(f"{cls:30} → {count} images")

# print("\nTotal images:", total_images)
# print("Total classes:", len(classes))

# pose_names = [name for name in sorted(os.listdir(train_dir)) if not name.startswith('.')]
# pose_to_id = {name: i for i, name in enumerate(pose_names)}
# print(pose_to_id)

# X = []
# y = []

# x = 1
# for pose_name in pose_names:
#     pose_folder = os.path.join(train_dir, pose_name)
#     print(pose_folder)
#     for img_file in os.listdir(pose_folder):
#         if not img_file.lower().endswith((".jpg", ".png", ".jpeg")):
#             continue

#         img_path = os.path.join(pose_folder, img_file)
#         print(img_path)

#         features = process_image(img_path)
#         if features is None:
#             continue

#         X.append(features)
#         y.append(pose_to_id[pose_name])
#         print(x)
#         x += 1

# X = np.array(X)
# y = np.array(y)

# print("X shape:", X.shape)
# print("y shape:", y.shape)

# """# Classifier: SVM"""

# from sklearn.model_selection import train_test_split

# X_train, X_valid, y_train, y_valid = train_test_split(
#     X, y, test_size=0.2, stratify=y, random_state=42
# )

# from sklearn.preprocessing import StandardScaler

# scaler = StandardScaler()
# X_train_scaled = scaler.fit_transform(X_train)
# X_valid_scaled = scaler.transform(X_valid)

# from sklearn.svm import SVC

# svm_model = SVC(
#     kernel='rbf',
#     C=10,
#     gamma='scale',
#     probability=True
# )

# svm_model.fit(X_train_scaled, y_train)

# from sklearn.metrics import accuracy_score, classification_report

# y_pred = svm_model.predict(X_valid_scaled)

# print("Accuracy:", accuracy_score(y_valid, y_pred))
# print(classification_report(y_valid, y_pred, target_names=pose_names))

# import pickle

# with open("svm_classifier.pkl", "wb") as f:
#     pickle.dump({
#         "model": svm_model,
#         "scaler": scaler,
#         "pose_names": pose_names
#     }, f)

# """# Test Model"""

# import pickle

# with open("svm_classifier.pkl", "rb") as f:
#     data = pickle.load(f)

# svm_model = data["model"]
# scaler = data["scaler"]
# pose_names = data["pose_names"]

# def classify_pose(img_path):
#     features = process_image(img_path)

#     if features is None:
#         return "Pose not detected"

#     features = features.reshape(1, -1)
#     features_scaled = scaler.transform(features)

#     pred_id = svm_model.predict(features_scaled)[0]
#     pred_name = pose_names[pred_id]

#     return pred_name

# img_path = "/content/test-img1.jpeg"
# classify_pose(img_path)

# img_path = "/content/test-img2.jpeg"
# classify_pose(img_path)